# Generated by Django 5.1.3 on 2024-12-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='password',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
    ]
