# Generated by Django 5.1.3 on 2024-12-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0004_alter_contact_address_alter_contact_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
    ]
