# Generated by Django 5.1.3 on 2024-12-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0005_remove_contact_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
