# Generated by Django 5.1.3 on 2024-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0006_contact_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='day',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
