# Generated by Django 5.1.3 on 2025-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0007_contact_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
